package org.omg.PortableServer;


/**
* org/omg/PortableServer/IMPLICIT_ACTIVATION_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /private/tmp/openjdkA8-20220228-18546-1kfawkm/jdk8u322-ga/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Monday, 28 February 2022 15:07:36 o'clock GMT
*/

public interface IMPLICIT_ACTIVATION_POLICY_ID
{

  /**
  	 * The value representing IMPLICIT_ACTIVATION_POLICY_ID.
  	 */
  public static final int value = (int)(20L);
}
