package org.omg.IOP;


/**
* org/omg/IOP/RMICustomMaxStreamFormat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /private/tmp/openjdkA8-20220228-18546-1kfawkm/jdk8u322-ga/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Monday, 28 February 2022 15:07:35 o'clock GMT
*/

public interface RMICustomMaxStreamFormat
{

  /**
       * Identifies a CDR encapsulation of the RMICustomMaxStreamFormat
       * service context which contains a single byte specifying
       * the client's maximum RMI-IIOP stream format version.
       *
       * See Java to IDL ptc/02-01-12 1.4.12.
       */
  public static final int value = (int)(17L);
}
