package org.omg.IOP;


/**
* org/omg/IOP/TAG_CODE_SETS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /private/tmp/openjdkA8-20220228-18546-1kfawkm/jdk8u322-ga/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Monday, 28 February 2022 15:07:35 o'clock GMT
*/

public interface TAG_CODE_SETS
{

  /**
       * The code set component of the IOR multi-component profile structure
       * contains:
       * <ul>
       *   <li>server's native char code set and conversion code sets, and</li>
       *   <li>server's native wchar code set and conversion code sets.</li>
       * </ul>
       * Both char and wchar conversion code sets are listed in order of 
       * preference.
       */
  public static final int value = (int)(1L);
}
